version: '3.8'
services:
  api:
    build: ./Backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  website:
    build: ./Frontend
    ports:
      - "8080:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
